version: "3"
services:
  portainer:
    image: portainer/portainer:1.11.4
    command: -H unix:///var/run/docker.sock  --no-auth
    ports:
      - 9001:9000
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
    deploy:
      placement:
            constraints: [node.labels.shathel.node.main == true]
      labels:
          com.df.notify: "true"
          com.df.distribute: "true"
          com.df.usersSecret: "monitoring"
          com.df.servicePath: "/portainer/,/portainer/api"
          com.df.reqPathReplace: /
          com.df.reqPathSearch: /portainer/
          com.df.port: "9000"


volumes:
  portainer-data: