version: "3"
services:
  service:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      9000:9000
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
            constraints: [node.role == manager]
