version: '3.1'
services:
  project1a:
    image: project(:):simple-project
    environment:
      - SAMPLE=@TOKEN_SAMPLE@
    ports:
      - 8080:8080
  project1b:
    image: project(:):dummyExtra
    ports:
      - 9091:9090

