# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest
services:
  - docker:dind
build:
  stage: build
  script:
    - docker pull sasol/dind4j:latest
    - >
      docker run --privileged -w /build -v $(pwd):/build --rm sasol/dind4j:latest
      ./gradlew --no-daemon --project-cache-dir=.cache --gradle-user-home=.cache clean assemble
  allow_failure: false
  tags:
  - shared
test:
  stage: test
  script:
    - docker pull sasol/dind4j:latest
    - >
      docker run --privileged -w /build -v $(pwd):/build --rm sasol/dind4j:latest
      ./gradlew --no-daemon --project-cache-dir=.cache --gradle-user-home=.cache clean test
  tags:
  - shared    