version: '3'

services:
  elasticsearch:
    image: elasticsearch:5.2.0-alpine
    command: -Enetwork.host=0.0.0.0
    networks:
      - network
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - /shathel-data/elastic:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms300m -Xmx300m"
    deploy:
      resources:
        limits:
            cpus: '0.5'
            memory: 700M
  kibana:
    image: kibana:5.2.0
    networks:
      - network
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.43.0/24