version: '3'

services:
  logstorage:
    image: elasticsearch:5.2.0-alpine
    command: -Enetwork.host=0.0.0.0
    networks:
      - network
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - /shathel-data/elastic:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms300m -Xmx300m"
    deploy:
      resources:
        limits:
            cpus: '0.5'
            memory: 550M
  kibana:
    build: ${PROXY_BUILD_TO_USE:-kibana/}
    environment:
      ELASTICSEARCH_URL: http://logstorage:9200
    networks:
      - network
#    volumes:
#      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    deploy:
      labels:
          com.df.notify: 'true'
          com.df.usersSecret: "monitoring"
          com.df.distribute: 'true'
          com.df.servicePath: "/kibana"
          com.df.reqPathReplace: /
          com.df.reqPathSearch: /kibana/
          com.df.port: '5601'
      resources:
        limits:
            cpus: '0.5'
            memory: 250M
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.43.0/24