version: "3"
services:
  consul:
    image: consul
    ports:
      - 8500:8500
    networks:
          - 00shathel_network
    environment:
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=$CONSUL_CLUSTER_SIZE -retry-join=consul
    deploy:
      mode: global
  consul-client:
      image: consul
      networks:
          - 00shathel_network
      environment:
        - 'CONSUL_BIND_INTERFACE=eth0'
        - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
      command: agent -retry-join=consul -rejoin
      deploy:
        mode: replicated
        replicas: 1

networks:
  00shathel_network:
    external: true