version: "3.1"
services:

  hw:
    image: crccheck/hello-world
    networks:
      - socating_discoverablee
    environment:
      - VIRTUAL_HOST=helloworld
    deploy:
      mode: global

networks:
  socating_discoverablee:
    external: true