version: "3.1"
services:
  dockerexposer:
    image: sasol/alpine-socat-openssl:3.5
    networks:
      - discoverablee
    command: -d -d openssl-listen:3333,fork,reuseaddr,cert=/run/secrets/server_pem,cafile=/run/secrets/client_crt unix-connect:/var/run/docker.sock
    ports:
      - 3333:3333
    secrets:
      - server_pem
      - client_crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
            constraints: [node.role == manager]
  dockergen:
    image: jwilder/docker-gen
    secrets:
      - server_crt
      - client_crt
      - client_key
    command: >
          -tlscacert /run/secrets/server_crt
          -tlscert /run/secrets/client_crt
          -tlskey /run/secrets/client_key
          -watch -endpoint tcp://dockerexposer:3333
          /tmp/nginx.tmpl /tmp-out/ngnix.conf
    networks:
      - discoverablee
    volumes:
#      - /tmp/nginx.tmpl:/tmp/nginx.tmpl
      - dummy:/tmp-out
    deploy:
      mode: global
  watcher:
    image: ubuntu
    volumes:
      - dummy:/tmp-out
    command: /bin/sh -c "while true; do echo ======================; cat /tmp-out/ngnix.conf; sleep 5s; done;"




networks:
  discoverablee:
volumes:
  dummy:
secrets:
  server_crt:
    file: ./tmp/server.crt
  server_key:
    file: ./tmp/server.key
  server_pem:
    file: ./tmp/server.pem
  client_crt:
    file: ./tmp/client.crt
  client_key:
    file: ./tmp/client.key
  client_pem:
    file: ./tmp/client.pem