version: '3'

services:
  metadata:
    image: ianneub/network-tools
    command: /bin/bash -c "until false; do ping tasks.metadata; sleep 1; done"
  filebeat:
    image: prima/filebeat:5.2.0
    deploy:
      mode: global
    hostname: "{{.Node.ID}}.filebeat"
    volumes:
        - ./filebeat/filebeat.yml:/filebeat.yml
        - ./filebeat/filebeat.template.json:/filebeat.template.json
        - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global