version: '3'

services:
  filebeat:
    image: prima/filebeat:5.2.0
    deploy:
      mode: global
    hostname: "{{.Node.ID}}.filebeat"
    volumes:
        - ./filebeat/filebeat.yml:/filebeat.yml
        - ./filebeat/filebeat.template.json:/filebeat.template.json
        - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global