---
- name: Check if docker machine provisioning is needed on node
  stat: path=/shathel-ansible/machine_provisioned_marker
  register: machine_provisioned_marker
- name: Provision with generic docker machine driver - on First because ansible,dmachine suck, and i am lazy as fuck.
  delegate_to: 127.0.0.1
  command: >
      docker-machine -s {{shathel_docker_machine_storage}} create --driver generic
      --generic-ip-address={{public_ip}}
      --generic-ssh-key={{shathel_docker_machine_key}}
      --generic-ssh-user={{shathel_docker_machine_user}}
      {{current_name}}
  become: no
  when: machine_provisioned_marker.stat.exists != true and private_ip == head_private_ip
- name: Provision with generic docker machine driver - on rest
  delegate_to: 127.0.0.1
  command: >
      docker-machine -s {{shathel_docker_machine_storage}} create --driver generic
      --generic-ip-address={{public_ip}}
      --generic-ssh-key={{shathel_docker_machine_key}}
      --generic-ssh-user={{shathel_docker_machine_user}}
      {{current_name}}
  become: no
  when: machine_provisioned_marker.stat.exists != true and private_ip != head_private_ip
- name: Leaving Provision Marker
  file:
    path: /shathel-ansible/machine_provisioned_marker
    state: touch
  when: machine_provisioned_marker.stat.exists != true