---
- hosts: "{{ shathel_manager_hosts }}"
  become: yes
  pre_tasks:
    - name: Ansible Dir present
      file:
        path: /shathel-ansible
        state: directory
#    - name: Update apt cache if needed.
#      apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: Remembering head node
        set_fact: head_node={{ groups[shathel_manager_hosts][0] }}
      - name: Saving Head node private ip
        set_fact: head_private_ip={{ hostvars[head_node].private_ip }}
      - name: Saving Node Index
        set_fact: current_index={{groups[shathel_manager_hosts].index(inventory_hostname)}}
      - name: Saving Node Name
        set_fact: current_name={{shathel_solution}}-manager-{{current_index}}
      - name: Saving Node Type
        set_fact: current_is_manager={{inventory_hostname in groups[shathel_manager_hosts]}}
      - name: Verifying node info
        debug: msg="name={{current_name}}, manager={{current_is_manager}}, head_ip={{head_private_ip}}, publicIp={{ public_ip }}, private_ip={{ private_ip }}"

      - include: tools.yml
      - include: initialize-machine.yml
      - include: initialize-swarm.yml

- hosts: "{{ shathel_worker_hosts }}"
  become: yes
  pre_tasks:
    - name: Ansible Dir present
      file:
        path: /shathel-ansible
        state: directory
#    - name: Update apt cache if needed.
#      apt: update_cache=yes cache_valid_time=3600
  tasks:
      - name: Remembering head node
        set_fact: head_node={{ groups[shathel_manager_hosts][0] }}
      - name: Saving Head node private ip
        set_fact: head_private_ip={{ hostvars[head_node].private_ip }}
      - name: Saving Node Index
        set_fact: current_index={{groups[shathel_worker_hosts].index(inventory_hostname)}}
      - name: Saving Node Name
        set_fact: current_name={{shathel_solution}}-worker-{{current_index}}
      - name: Saving Node Type
        set_fact: current_is_manager={{inventory_hostname in groups[shathel_manager_hosts]}}
      - name: Verifying node info
        debug: msg="name={{current_name}}, manager={{current_is_manager}}, head_ip={{head_private_ip}}, publicIp={{ public_ip }}, private_ip={{ private_ip }}"

      - include: tools.yml
      - include: initialize-machine.yml
      - include: initialize-swarm.yml
