version: '3'
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.44.0/24

volumes:
    grafana-data:
    prometheus-data:
services:
  nodeexporter:
    build: ./node-exporter
    deploy:
      mode: global
    networks:
        - network
    volumes:
        - /proc:/host/proc
        - /sys:/host/sys
        - /:/rootfs
        - /etc/hostname:/etc/host_hostname
    environment:
        - HOST_HOSTNAME=/etc/host_hostname
    command: >
              -collector.procfs /host/proc
              -collector.sysfs /host/sys
              -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
              --collector.textfile.directory /etc/node-exporter/
              --collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"
  cadvisor:
      image: google/cadvisor:v0.24.1
      deploy:
        mode: global
      networks:
          - network
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
      image: prom/prometheus:v1.5.2
      networks:
          - network
      ports:
        - 9090:9090
      volumes:
          - prometheus-data:/prometheus
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command: >
            -config.file=/etc/prometheus/prometheus.yml
            -storage.local.path=/prometheus
            -web.console.libraries=/etc/prometheus/console_libraries
            -web.console.templates=/etc/prometheus/consoles
  grafana:
      build: ./grafana
      networks:
          - network
      ports:
        - 3000:3000
      volumes:
        - grafana-data:/var/lib/grafana
        - ./grafana_dashboards/:/var/lib/grafana/dashboards
      environment:
          - GF_SERVER_ROOT_URL=http://grafana.swarm
          - GF_SECURITY_ADMIN_PASSWORD=adminadmin
          - PROMETHEUS_ENDPOINT=http://prometheus:9090
#          - DASHBOARDS_IMPORT=609:20

