version: '3'
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.45.0/24

volumes:
    grafana-data:
    prometheus-data:
services:
  nodeexporter:
    build: ./node-exporter
    deploy:
      mode: global
    networks:
        - network
    volumes:
        - /proc:/host/proc
        - /sys:/host/sys
        - /:/rootfs
        - /etc/hostname:/etc/host_hostname
    environment:
        - HOST_HOSTNAME=/etc/host_hostname
    command: >
              -collector.procfs /host/proc
              -collector.sysfs /host/sys
              -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
              --collector.textfile.directory /etc/node-exporter/
              --collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"
  cadvisor:
      image: google/cadvisor:v0.24.1
      deploy:
        mode: global
      networks:
          - network
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
      image: prom/prometheus:v1.5.2
      networks:
          - network
      ports:
        - 9090:9090
      volumes:
          - prometheus-data:/prometheus
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command: >
            -config.file=/etc/prometheus/prometheus.yml
            -storage.local.path=/prometheus
            -web.console.libraries=/etc/prometheus/console_libraries
            -web.console.templates=/etc/prometheus/consoles
            -web.external-url=http://${SHATHEL_ENV_DOMAIN}${PROMETHEUS_CONTEXT_PATH:-/}
            -web.route-prefix=${PROMETHEUS_CONTEXT_PATH:-/}
      deploy:
        labels:
            com.df.notify: "true"
            com.df.usersSecret: "monitoring"
            com.df.distribute: "true"
            com.df.servicePath: "/prometheus"
            com.df.port: "9090"
  grafana:
      image: grafana/grafana:4.1.1
      networks:
          - network
      deploy:
        resources:
          limits:
              cpus: '0.5'
              memory: 300M
        labels:

          com.df.notify: 'true'
          com.df.usersSecret: "monitoring"
          com.df.distribute: 'true'
          com.df.servicePath: "/grafana/,/grafana/public,/grafana/api"
          com.df.reqPathReplace: /
          com.df.reqPathSearch: /grafana/
          com.df.port: '3000'
      ports:
        - 3000:3000
      volumes:
        - grafana-data:/var/lib/grafana
        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
        - ./grafana_dashboards/:/var/lib/grafana/dashboards
      environment:
        - GF_SERVER_DOMAIN=$SHATHEL_ENV_DOMAIN
        - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s${GRAFANA_CONTEXT_PATH:-/}
        - GF_AUTH_ANONYMOUS_ENABLED=true
#        - GF_AUTH_BASIC_ENABLED=false
#          - DASHBOARDS_IMPORT=609:20

