version: "3.1"
services:
  dockerexposer:
    image: sasol/alpine-socat-openssl:3.5
    networks:
      - discoverablee
    command: -d -d openssl-listen:3333,fork,reuseaddr,cert=/run/secrets/server_pem,cafile=/run/secrets/client_crt unix-connect:/var/run/docker.sock
    ports:
      - 3333:3333
    secrets:
      - server_pem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock





networks:
  discoverablee:
volumes:
  dummy:
secrets:
  server_pem:
    file: ./server.pem
