version: "3.1"
services:
  dockerexposer:
    image: sasol/alpine-socat-openssl:3.5
    networks:
      - discoverablee
    command: -d -d openssl-listen:3333,fork,reuseaddr,cert=/run/secrets/server_pem,cafile=/run/secrets/client_crt unix-connect:/var/run/docker.sock
    ports:
      - 3333:3333
    secrets:
      - server_pem
      - client_crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
            constraints: [node.role == manager]
  ngnix:
      image: nginx
      volumes:
        - /mnt/sda1/nginx-conf.d:/etc/nginx/conf.d
      ports:
        - 80:80
      networks:
        - discoverablee
  dockergen:
    image: 111.111.111.99:4000/sasol/docker-gen:latest
    secrets:
      - server_crt
      - client_pem
      - client_crt
      - client_key
    command: >
          -tlscacert /run/secrets/server_crt
          -tlscert /run/secrets/client_crt
          -tlskey /run/secrets/client_key
          -swarm -notify-by-volumes
          -watch -endpoint dockerexposer:3333
          /templates/nginx-swarm.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - discoverablee
    volumes:
      - /mnt/sda1/nginx-templates:/templates/
      - /mnt/sda1/nginx-conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global




networks:
  discoverablee:
secrets:
  server_crt:
    file: ./tmp/server.crt
  server_key:
    file: ./tmp/server.key
  server_pem:
    file: ./tmp/server.pem
  client_crt:
    file: ./tmp/client.crt
  client_key:
    file: ./tmp/client.key
  client_pem:
    file: ./tmp/client.pem